In [1]:
#import basic libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_excel('flight_price.xlsx')

In [3]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [5]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [6]:
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662

In [7]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [8]:
#convert dates in numerical form by converting into date month and year column
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [9]:
df[['Date']].dtypes

Date    object
dtype: object

In [10]:
#date monnth year are in string but it should be numerical form

In [11]:
df['Date']=df['Date'].astype(int)
df['Month']=df['Date'].astype(int)
df['Year']=df['Date'].astype(int)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [13]:
df.drop('Date_of_Journey',axis=1,inplace=True)

In [14]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,24,24
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,1,1
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,9,9
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,12,12
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,1,1

In [15]:
## Change the Arrival Time into hours and minutes

df['Arrival_Hours'] = df['Arrival_Time'].str[0:5].str.split(':').str[0]

In [16]:
df['Arrival_minutes'] = df['Arrival_Time'].str[0:5].str.split(':').str[1]

In [17]:
# Type casting into integer

In [18]:
df['Arrival_Hours'] = df['Arrival_Hours'].astype(int)

In [19]:
df['Arrival_minutes'] = df['Arrival_minutes'].astype(int)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
 13  Arrival_Hours    10683 non-null  int64
 14  Arrival_minutes  10683 non-null  int64
dtypes: int64(6), object(9)
memory usage: 1.2+ MB

In [21]:
df.drop('Arrival_Time',axis=1,inplace=True)

In [22]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,24,24,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,1,1,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,9,9,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,12,12,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,1,1,21,35

In [23]:
df['Dep_Hours'] = df['Dep_Time'].str.split(':').str[0]
df['Dep_Minutes'] = df['Dep_Time'].str.split(':').str[1]

In [24]:
#change into integer type

In [25]:
df['Dep_Hours']=df['Dep_Hours'].astype(int)
df['Dep_Minutes']=df['Dep_Minutes'].astype(int)

In [26]:
df.drop('Dep_Time',axis=1,inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10683 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   Month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Arrival_Hours    10683 non-null  int64
 12  Arrival_minutes  10683 non-null  int64
 13  Dep_Hours        10683 non-null  int64
 14  Dep_Minutes      10683 non-null  int64
dtypes: int64(8), object(7)
memory usage: 1.2+ MB

In [28]:
df.drop('Route',axis=1,inplace=True)

In [29]:
df['Duration_Hours'] = df['Duration'].str[0:].str.split().str[0].str.split('h').str[0]

In [30]:
df['Duration_Minutes'] = df['Duration'].str[0:].str.split().str[1].str.split('m').str[0]

In [31]:
df[df['Duration'].str[0:] == '5m']

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_minutes,Dep_Hours,Dep_Minutes,Duration_Hours,Duration_Minutes
6474,Air India,Mumbai,Hyderabad,5m,2 stops,No info,17327,6,6,6,16,55,16,50,5m,NaN

In [32]:
df.drop('Duration',axis=1,inplace=True)

In [33]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_minutes,Dep_Hours,Dep_Minutes,Duration_Hours,Duration_Minutes
0,IndiGo,Banglore,New Delhi,non-stop,No info,3897,24,24,24,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2 stops,No info,7662,1,1,1,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,2 stops,No info,13882,9,9,9,4,25,9,25,19,NaN
3,IndiGo,Kolkata,Banglore,1 stop,No info,6218,12,12,12,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,1 stop,No info,13302,1,1,1,21,35,16,50,4,45

In [34]:
df['Total_Stops']

0        non-stop
1         2 stops
2         2 stops
3          1 stop
4          1 stop
           ...
10678    non-stop
10679    non-stop
10680    non-stop
10681    non-stop
10682     2 stops
Name: Total_Stops, Length: 10683, dtype: object

In [35]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [36]:
df['Total_Stops'].mode()

0    1 stop
Name: Total_Stops, dtype: object

In [37]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0, '2 stops': 2, '1 stop': 1, '3 stops' : 3, np.nan : 1 , '4 stops' : 4})

In [38]:
df['Total_Stops'].value_counts()

1    5626
0    3491
2    1520
3      45
4       1
Name: Total_Stops, dtype: int64

In [39]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_minutes,Dep_Hours,Dep_Minutes,Duration_Hours,Duration_Minutes
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,24,24,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2,No info,7662,1,1,1,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,9,9,4,25,9,25,19,NaN
3,IndiGo,Kolkata,Banglore,1,No info,6218,12,12,12,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,1,No info,13302,1,1,1,21,35,16,50,4,45

In [40]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [41]:
df['Source'].unique()

array(['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai'], dtype=object)

In [42]:
df['Destination'].unique()

array(['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad'],
      dtype=object)

In [43]:
from sklearn.preprocessing import OneHotEncoder

In [44]:
OHE = OneHotEncoder()

In [45]:
OHE_array = OHE.fit_transform(df[['Airline','Source','Destination']]).toarray()

In [46]:
OHE_df = pd.DataFrame(OHE_array,columns=OHE.get_feature_names_out())

In [47]:
df = pd.concat([df,OHE_df],axis=1)

In [48]:
df.drop(['Airline','Source','Destination'],axis=1,inplace=True)

In [49]:
df.head()

,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_minutes,Dep_Hours,Dep_Minutes,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,0,No info,3897,24,24,24,1,10,22,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,No info,7662,1,1,1,13,15,5,50,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,2,No info,13882,9,9,9,4,25,9,25,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1,No info,6218,12,12,12,23,30,18,5,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1,No info,13302,1,1,1,21,35,16,50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [50]:
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [51]:
df['Additional_Info'].value_counts()

No info                         8345
In-flight meal not included     1982
No check-in baggage included     320
1 Long layover                    19
Change airports                    7
Business class                     4
No Info                            3
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: Additional_Info, dtype: int64

In [52]:
OHE_Add_info = OHE.fit_transform(df[['Additional_Info']]).toarray()

In [53]:
df1 = pd.DataFrame(OHE_Add_info,columns=OHE.get_feature_names_out())

In [54]:
df = pd.concat([df,df1],axis=1)

In [55]:
df.drop('Additional_Info',axis=1,inplace=True)

In [56]:
df.head()

,Total_Stops,Price,Date,Month,Year,Arrival_Hours,Arrival_minutes,Dep_Hours,Dep_Minutes,Duration_Hours,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0,3897,24,24,24,1,10,22,20,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2,7662,1,1,1,13,15,5,50,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2,13882,9,9,9,4,25,9,25,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6218,12,12,12,23,30,18,5,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,13302,1,1,1,21,35,16,50,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [57]:
df.isnull().sum()

Total_Stops                                        0
Price                                              0
Date                                               0
Month                                              0
Year                                               0
Arrival_Hours                                      0
Arrival_minutes                                    0
Dep_Hours                                          0
Dep_Minutes                                        0
Duration_Hours                                     0
Duration_Minutes                                1032
Airline_Air Asia                                   0
Airline_Air India                                  0
Airline_GoAir                                      0
Airline_IndiGo                                     0
Airline_Jet Airways                                0
Airline_Jet Airways Business                       0
Airline_Multiple carriers                          0
Airline_Multiple carriers Premium economy          0
Airline_SpiceJet                                   0
Airline_Trujet                                     0
Airline_Vistara                                    0
Airline_Vistara Premium economy                    0
Source_Banglore                                    0
Source_Chennai                                     0
Source_Delhi                                       0
Source_Kolkata                                     0
Source_Mumbai                                      0
Destination_Banglore                               0
Destination_Cochin                                 0
Destination_Delhi                                  0
Destination_Hyderabad                              0
Destination_Kolkata                                0
Destination_New Delhi                              0
Additional_Info_1 Long layover                     0
Additional_Info_1 Short layover                    0
Additional_Info_2 Long layover                     0
Additional_Info_Business class                     0
Additional_Info_Change airports                    0
Additional_Info_In-flight meal not included        0
Additional_Info_No Info                            0
Additional_Info_No check-in baggage included       0
Additional_Info_No info                            0
Additional_Info_Red-eye flight                     0
dtype: int64

In [58]:
df['Duration_Minutes'].fillna(df['Duration_Minutes'].mode()[0],inplace=True)

In [59]:
df.isnull().sum()

Total_Stops                                     0
Price                                           0
Date                                            0
Month                                           0
Year                                            0
Arrival_Hours                                   0
Arrival_minutes                                 0
Dep_Hours                                       0
Dep_Minutes                                     0
Duration_Hours                                  0
Duration_Minutes                                0
Airline_Air Asia                                0
Airline_Air India                               0
Airline_GoAir                                   0
Airline_IndiGo                                  0
Airline_Jet Airways                             0
Airline_Jet Airways Business                    0
Airline_Multiple carriers                       0
Airline_Multiple carriers Premium economy       0
Airline_SpiceJet                                0
Airline_Trujet                                  0
Airline_Vistara                                 0
Airline_Vistara Premium economy                 0
Source_Banglore                                 0
Source_Chennai                                  0
Source_Delhi                                    0
Source_Kolkata                                  0
Source_Mumbai                                   0
Destination_Banglore                            0
Destination_Cochin                              0
Destination_Delhi                               0
Destination_Hyderabad                           0
Destination_Kolkata                             0
Destination_New Delhi                           0
Additional_Info_1 Long layover                  0
Additional_Info_1 Short layover                 0
Additional_Info_2 Long layover                  0
Additional_Info_Business class                  0
Additional_Info_Change airports                 0
Additional_Info_In-flight meal not included     0
Additional_Info_No Info                         0
Additional_Info_No check-in baggage included    0
Additional_Info_No info                         0
Additional_Info_Red-eye flight                  0
dtype: int64

In [60]:
df.dtypes

Total_Stops                                       int64
Price                                             int64
Date                                              int64
Month                                             int64
Year                                              int64
Arrival_Hours                                     int64
Arrival_minutes                                   int64
Dep_Hours                                         int64
Dep_Minutes                                       int64
Duration_Hours                                   object
Duration_Minutes                                 object
Airline_Air Asia                                float64
Airline_Air India                               float64
Airline_GoAir                                   float64
Airline_IndiGo                                  float64
Airline_Jet Airways                             float64
Airline_Jet Airways Business                    float64
Airline_Multiple carriers                       float64
Airline_Multiple carriers Premium economy       float64
Airline_SpiceJet                                float64
Airline_Trujet                                  float64
Airline_Vistara                                 float64
Airline_Vistara Premium economy                 float64
Source_Banglore                                 float64
Source_Chennai                                  float64
Source_Delhi                                    float64
Source_Kolkata                                  float64
Source_Mumbai                                   float64
Destination_Banglore                            float64
Destination_Cochin                              float64
Destination_Delhi                               float64
Destination_Hyderabad                           float64
Destination_Kolkata                             float64
Destination_New Delhi                           float64
Additional_Info_1 Long layover                  float64
Additional_Info_1 Short layover                 float64
Additional_Info_2 Long layover                  float64
Additional_Info_Business class                  float64
Additional_Info_Change airports                 float64
Additional_Info_In-flight meal not included     float64
Additional_Info_No Info                         float64
Additional_Info_No check-in baggage included    float64
Additional_Info_No info                         float64
Additional_Info_Red-eye flight                  float64
dtype: object

In [61]:
df[df['Duration_Hours']=='5m'].index[0]

6474

In [62]:
df.drop(6474,inplace=True)

In [65]:
df['Duration_Hours'] = df['Duration_Hours'].astype(int)
df['Duration_Minutes'] = df['Duration_Minutes'].astype(int)

In [66]:
df.dtypes

Total_Stops                                       int64
Price                                             int64
Date                                              int64
Month                                             int64
Year                                              int64
Arrival_Hours                                     int64
Arrival_minutes                                   int64
Dep_Hours                                         int64
Dep_Minutes                                       int64
Duration_Hours                                    int64
Duration_Minutes                                  int64
Airline_Air Asia                                float64
Airline_Air India                               float64
Airline_GoAir                                   float64
Airline_IndiGo                                  float64
Airline_Jet Airways                             float64
Airline_Jet Airways Business                    float64
Airline_Multiple carriers                       float64
Airline_Multiple carriers Premium economy       float64
Airline_SpiceJet                                float64
Airline_Trujet                                  float64
Airline_Vistara                                 float64
Airline_Vistara Premium economy                 float64
Source_Banglore                                 float64
Source_Chennai                                  float64
Source_Delhi                                    float64
Source_Kolkata                                  float64
Source_Mumbai                                   float64
Destination_Banglore                            float64
Destination_Cochin                              float64
Destination_Delhi                               float64
Destination_Hyderabad                           float64
Destination_Kolkata                             float64
Destination_New Delhi                           float64
Additional_Info_1 Long layover                  float64
Additional_Info_1 Short layover                 float64
Additional_Info_2 Long layover                  float64
Additional_Info_Business class                  float64
Additional_Info_Change airports                 float64
Additional_Info_In-flight meal not included     float64
Additional_Info_No Info                         float64
Additional_Info_No check-in baggage included    float64
Additional_Info_No info                         float64
Additional_Info_Red-eye flight                  float64
dtype: object

In [67]:
df.corr()

,Total_Stops,Price,Date,Month,Year,Arrival_Hours,Arrival_minutes,Dep_Hours,Dep_Minutes,Duration_Hours,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
Total_Stops,1.000000,0.603768,-0.009329,-0.009329,-0.009329,0.038066,-0.107270,-0.061599,-0.002814,0.740224,...,0.010999,0.016854,0.016854,0.005043,0.044603,0.105815,0.004367,-0.201501,-0.021216,-0.011811
Price,0.603768,1.000000,-0.153619,-0.153619,-0.153619,0.024203,-0.086489,0.006718,-0.024726,0.508985,...,0.119233,0.037054,0.036502,0.200339,0.042845,0.039912,-0.003787,-0.207386,0.022145,0.003750
Date,-0.009329,-0.153619,1.000000,1.000000,1.000000,-0.003160,-0.017362,0.002271,-0.008149,-0.022283,...,-0.056249,-0.014275,-0.014275,-0.028554,-0.037779,0.036156,-0.024727,0.033426,-0.036362,-0.014275
Month,-0.009329,-0.153619,1.000000,1.000000,1.000000,-0.003160,-0.017362,0.002271,-0.008149,-0.022283,...,-0.056249,-0.014275,-0.014275,-0.028554,-0.037779,0.036156,-0.024727,0.033426,-0.036362,-0.014275
Year,-0.009329,-0.153619,1.000000,1.000000,1.000000,-0.003160,-0.017362,0.002271,-0.008149,-0.022283,...,-0.056249,-0.014275,-0.014275,-0.028554,-0.037779,0.036156,-0.024727,0.033426,-0.036362,-0.014275
Arrival_Hours,0.038066,0.024203,-0.003160,-0.003160,-0.003160,1.000000,-0.154453,0.005193,0.043008,0.055228,...,-0.000525,0.013615,-0.006134,-0.003100,0.021632,-0.016775,0.008923,-0.087713,0.050630,-0.016009
Arrival_minutes,-0.107270,-0.086489,-0.017362,-0.017362,-0.017362,-0.154453,1.000000,0.067816,-0.017833,-0.074249,...,0.009549,0.000183,0.000183,-0.001100,0.001593,-0.045545,0.003702,-0.002665,0.042941,-0.008611
Dep_Hours,-0.061599,0.006718,0.002271,0.002271,0.002271,0.005193,0.067816,1.000000,-0.024887,0.002852,...,0.003356,-0.007558,-0.010925,-0.021852,-0.011730,0.057648,-0.000458,-0.010214,-0.048544,0.017690
Dep_Minutes,-0.002814,-0.024726,-0.008149,-0.008149,-0.008149,0.043008,-0.017833,-0.024887,1.000000,-0.021795,...,0.029151,0.013195,0.010617,0.022526,0.012503,-0.001646,0.003505,0.062014,-0.029524,0.000305
Duration_Hours,0.740224,0.508985,-0.022283,-0.022283,-0.022283,0.055228,-0.074249,0.002852,-0.021795,1.000000,...,0.023095,0.004275,0.017943,-0.011385,0.016481,0.192724,-0.012326,-0.172029,-0.112910,-0.009394
Duration_Minutes,-0.139076,-0.112487,0.000701,0.000701,0.000701,-0.075485,0.095377,-0.028787,0.038159,-0.122932,...,-0.006774,0.002573,0.005981,0.008555,-0.024115,-0.041881,0.010360,0.005333,0.038119,0.009389
Airline_Air Asia,-0.094412,-0.133034,0.008926,0.008926,0.008926,-0.034975,0.078303,0.045980,0.158220,-0.104357,...,-0.007406,-0.001698,-0.001698,-0.003396,-0.004493,-0.083742,-0.002941,-0.030832,0.091542,0.055149
Airline_Air India,0.270819,0.049987,-0.032490,-0.032490,-0.032490,0.088656,0.060856,-0.013136,-0.045745,0.262270,...,0.017317,0.021852,0.021852,-0.008570,0.057833,-0.211342,-0.007421,-0.077812,0.225210,-0.004284
Airline_GoAir,-0.060100,-0.095138,-0.003122,-0.003122,-0.003122,0.018539,0.096877,-0.016358,0.076757,-0.094075,...,-0.005741,-0.001316,-0.001316,-0.002632,-0.003483,-0.064915,-0.002280,-0.023901,0.071993,-0.001316
Airline_IndiGo,-0.302965,-0.361025,0.007281,0.007281,0.007281,-0.071443,0.035213,-0.023339,-0.014703,-0.346340,...,-0.020590,-0.004720,-0.004720,-0.009441,-0.012490,-0.232813,0.034362,-0.085717,0.256472,-0.004720
Airline_Jet Airways,0.215197,0.416334,-0.017304,-0.017304,-0.017304,-0.027305,-0.057580,0.114028,0.024475,0.306994,...,0.023850,-0.007262,-0.007262,-0.004448,-0.019219,0.587797,-0.012580,-0.131893,-0.498261,-0.007262
Airline_Jet Airways Business,0.017882,0.253344,-0.031713,-0.031713,-0.031713,-0.014454,0.005237,-0.007521,0.009169,-0.011852,...,-0.001001,-0.000229,-0.000229,0.612200,-0.000607,-0.011315,-0.000397,-0.004166,-0.016118,-0.000229
Airline_Multiple carriers,0.118465,0.139884,0.042163,0.042163,0.042163,0.067963,-0.167421,-0.149952,-0.109364,-0.008160,...,-0.014989,-0.003436,-0.003436,-0.006872,-0.009093,-0.096162,-0.005951,-0.062399,0.119027,-0.003436
Airline_Multiple carriers Premium economy,0.009095,0.017659,0.030839,0.030839,0.030839,0.013494,-0.001780,-0.028668,-0.004624,-0.002280,...,-0.001473,-0.000338,-0.000338,-0.000676,-0.000894,-0.016661,-0.000585,-0.006134,0.018478,-0.000338
Airline_SpiceJet,-0.274349,-0.296550,0.022154,0.022154,0.022154,-0.090030,0.012594,-0.010418,0.092645,-0.263907,...,-0.003801,-0.002786,-0.002786,-0.005574,-0.007374,-0.137449,-0.004827,0.610243,-0.120868,-0.002786
Airline_Trujet,0.002521,-0.010380,-0.008569,-0.008569,-0.008569,0.003740,-0.002748,0.000858,-0.010007,-0.008255,...,-0.000408,-0.000094,-0.000094,-0.000187,-0.000248,-0.004618,-0.000162,-0.001700,0.005122,-0.000094
Airline_Vistara,-0.120434,-0.060619,-0.013169,-0.013169,-0.013169,0.068853,0.069470,0.023931,-0.077900,-0.020412,...,-0.009146,-0.002097,-0.002097,-0.004194,-0.005548,-0.103418,-0.003632,-0.038076,0.114694,-0.002097
Airline_Vistara Premium economy,-0.020460,-0.000451,-0.020115,-0.020115,-0.020115,0.000777,0.000317,-0.003373,-0.011380,-0.016272,...,-0.000708,-0.000162,-0.000162,-0.000324,-0.000429,-0.008000,-0.000281,-0.002945,0.008872,-0.000162
Source_Banglore,-0.368305,-0.117960,-0.050438,-0.050438,-0.050438,-0.024370,0.091094,-0.007829,0.077369,-0.274033,...,0.077459,0.019015,0.019015,0.038036,0.050324,-0.039111,0.032939,0.016555,0.014487,0.019015
Source_Chennai,-0.234764,-0.179211,0.006611,0.006611,0.006611,-0.014777,-0.030465,-0.014824,0.067117,-0.186710,...,-0.008118,-0.001861,-0.001861,-0.003722,-0.004925,-0.091794,-0.003223,0.143869,0.028555,-0.001861
Source_Delhi,0.490393,0.270813,0.099917,0.099917,0.099917,-0.006828,-0.209759,-0.118793,-0.085305,0.299865,...,-0.031776,-0.008314,-0.008314,-0.016631,-0.022003,0.032241,-0.014402,-0.133224,0.031158,-0.008314
Source_Kolkata,0.032849,0.009480,-0.060558,-0.060558,-0.060558,0.054750,0.118695,0.155540,-0.024224,0.123366,...,-0.025592,-0.005866,-0.005866,-0.011734,-0.015525,0.053940,-0.010162,0.032200,-0.059046,-0.005866
Source_Mumbai,-0.261587,-0.231568,-0.013704,-0.013704,-0.013704,-0.033655,0.080612,-0.017505,0.037221,-0.233083,...,-0.011144,-0.002554,-0.002554,-0.005110,-0.006760,-0.028433,-0.004425,0.073763,-0.001527,-0.002554
Destination_Banglore,0.032849,0.009480,-0.060558,-0.060558,-0.060558,0.054750,0.118695,0.155540,-0.024224,0.123366,...,-0.025592,-0.005866,-0.005866,-0.011734,-0.015525,0.053940,-0.010162,0.032200,-0.059046,-0.005866
Destination_Cochin,0.490393,0.270813,0.099917,0.099917,0.099917,-0.006828,-0.209759,-0.118793,-0.085305,0.299865,...,-0.031776,-0.008314,-0.008314,-0.016631,-0.022003,0.032241,-0.014402,-0.133224,0.031158,-0.008314
Destination_Delhi,-0.447401,-0.313388,0.002632,0.002632,0.002632,-0.030831,0.095328,0.009511,0.003209,-0.346272,...,-0.015471,-0.003546,-0.003546,-0.007094,-0.009385,-0.040035,-0.006143,0.044368,0.022335,-0.003546
Destination_Hyderabad,-0.261587,-0.231568,-0.013704,-0.013704,-0.013704,-0.033655,0.080612,-0.017505,0.037221,-0.233083,...,-0.011144,-0.002554,-0.002554,-0.005110,-0.006760,-0.028433,-0.004425,0.073763,-0.001527,-0.002554
Destination_Kolkata,-0.234764,-0.179211,0.006611,0.006611,0.006611,-0.014777,-0.030465,-0.014824,0.067117,-0.186710,...,-0.008118,-0.001861,-0.001861,-0.003722,-0.004925,-0.091794,-0.003223,0.143869,0.028555,-0.001861
Destination_New Delhi,-0.015261,0.189866,-0.075254,-0.075254,-0.075254,0.000395,0.021327,-0.022103,0.107140,0.003973,...,0.128658,0.031296,0.031296,0.062601,0.082825,-0.010179,0.054211,-0.027088,-0.004822,0.031296
Additional_Info_1 Long layover,0.010999,0.119233,-0.056249,-0.056249,-0.056249,-0.000525,0.009549,0.003356,0.029151,0.023095,...,1.000000,-0.000408,-0.000408,-0.000817,-0.001081,-0.020148,-0.000708,-0.007418,-0.079745,-0.000408
Additional_Info_1 Short layover,0.016854,0.037054,-0.014275,-0.014275,-0.014275,0.013615,0.000183,-0.007558,0.013195,0.004275,...,-0.000408,1.000000,-0.000094,-0.000187,-0.000248,-0.004618,-0.000162,-0.001700,-0.018279,-0.000094
Additional_Info_2 Long layover,0.016854,0.036502,-0.014275,-0.014275,-0.014275,-0.006134,0.000183,-0.010925,0.010617,0.017943,...,-0.000408,-0.000094,1.000000,-0.000187,-0.000248,-0.004618,-0.000162,-0.001700,-0.018279,-0.000094
Additional_Info_Business class,0.005043,0.200339,-0.028554,-0.028554,-0.028554,-0.003100,-0.001100,-0.021852,0.022526,-0.011385,...,-0.000817,-0.000187,-0.000187,1.000000,-0.000496,-0.009238,-0.000324,-0.003401,-0.036564,-0.000187
Additional_Info_Change airports,0.044603,0.042845,-0.037779,-0.037779,-0.037779,0.021632,0.001593,-0.011730,0.012503,0.016481,...,-0.001081,-0.000248,-0.000248,-0.000496,1.000000,-0.012222,-0.000429,-0.004500,-0.048376,-0.000248
Additional_Info_In-flight meal not included,0.105815,0.039912,0.036156,0.036156,0.036156,-0.016775,-0.045545,0.057648,-0.001646,0.192724,...,-0.020148,-0.004618,-0.004618,-0.009238,-0.012222,1.000000,-0.008000,-0.083877,-0.901690,-0.004618
Additional_Info_No Info,0.004367,-0.003787,-0.024727,-0.024727,-0.024727,0.008923,0.003702,-0.000458,0.003505,-0.012326,...,-0.000708,-0.000162,-0.000162,-0.000324,-0.000429,-0.008000,1.000000,-0.002945,-0.031664,-0.000162
Additional_Info_No check-in baggage included,-0.201501,-0.207386,0.033426,0.033426,0.033426,-0.087713,-0.002665,-0.010214,0.062014,-0.172029,...,-0.007418,-0.001700,-0.001700,-0.003401,-0.004500,-0.083877,-0.002945,1.000000,-0.331985,-0.001700
Additional_Info_No info,-0.021216,0.022145,-0.036362,-0.036362,-0.036362,0.050630,0.042941,-0.048544,-0.029524,-0.112910,...,-0.079745,-0.018279,-0.018279,-0.036564,-0.048376,-0.901690,-0.031664,-0.331985,1.000000,-0.018279
Additional_Info_Red-eye flight,-0.011811,0.003750,-0.014275,-0.014275,-0.014275,-0.016009,-0.008611,0.017690,0.000305,-0.009394,...,-0.000408,-0.000094,-0.000094,-0.000187,-0.000248,-0.004618,-0.000162,-0.001700,-0.018279,1.000000

In [69]:
df.to_csv('Flight_price_preprocessed.csv')